version: '3.1'

services:
  camunda:
    container_name: camunda
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./config/default.yml:/camunda/configuration/default.yml
      - ./config/web.xml:/camunda/webapps/engine-rest/WEB-INF/web.xml